### ISSUE TITLE
Please remove caffe2 include

### ISSUE THREAD

**Issue by jinfagang** [facebookresearch/d2go#144] opened 2021-11-26 07:34 UTC
I am using torch1.11 `'1.11.0.dev20211125+cu111'`
since d2go need torch.ao.quantization imports.

But I got error:

```
from caffe2.proto import caffe2_pb2, metanet_pb2, torch_pb2
ImportError: cannot import name 'metanet_pb2' from 'caffe2.proto'
```

that's a little embrassing. I need torch1.11 for torch.ao, but it doesn't have caffe2.... but I need caffe2 in d2go....

**Comment by zhanghang1989** [comment] 2021-11-28 18:22
This sounds like pytorch issue. We don't import "metanet_pb2" in d2go

**Comment by ppwwyyxx** [comment] 2021-11-29 02:57
Duplicate of #137

**Closed by ppwwyyxx** 2021-11-29 02:57 UTC
Labels: bug

**Comment by jinfagang** [comment] 2021-11-29 03:39
@zhanghang1989 I think d2go used caffe2 for mobile deployment.

![image](https://user-images.githubusercontent.com/21303438/143805031-9df60137-d0c9-4f24-b1d2-fe98e173c9c0.png)

I am addressing this issue because of it made users confusing.

**Comment by zhanghang1989** [comment] 2021-11-30 06:35
This issue should be already fixed by https://github.com/facebookresearch/d2go/pull/146

**Comment by jinfagang** [comment] 2021-12-01 06:08
@zhanghang1989 Please merge this PR is possible.

**Comment by zhanghang1989** [comment] 2021-12-01 17:50
> 

That PR is already merged. If you still experiencing the issue. Try install pytorch nightly
