### ISSUE TITLE
pretrained models with cocodataset in model zoo is not available

### ISSUE THREAD

**Issue by matiassotomejias** [facebookresearch/d2go#681] opened 2024-12-03 17:25 UTC
The models pretrained checkpoints is not availabled in model zoo and de aws bucket

WARNING:mobile_cv.arch.utils.helper:Arguments ['width_divisor', 'dw_skip_bnrelu', 'zero_last_bn_gamma'] skipped for op Conv2d
model_0409999.pth: 0.00B [00:00, ?B/s]
ERROR:iopath.common.download:Failed to download https://mobile-cv.s3-us-west-2.amazonaws.com/d2go/models/287445123/model_0409999.pth
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
[<ipython-input-21-e889e7bfd62b>](https://localhost:8080/#) in <cell line: 3>()
      1 from d2go.model_zoo import model_zoo
      2 selected_model = "mask_rcnn_fbnetv3g_fpn.yaml"
----> 3 model = model_zoo.get(selected_model, trained = True)

11 frames
[/usr/lib/python3.10/urllib/request.py](https://localhost:8080/#) in http_error_default(self, req, fp, code, msg, hdrs)
    641 class HTTPDefaultErrorHandler(BaseHandler):
    642     def http_error_default(self, req, fp, code, msg, hdrs):
--> 643         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    644 
    645 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 404: Not Found

**Comment by wat3rBro** [comment] 2024-12-12 07:30
Duplicate of #663

**Closed as completed by wat3rBro** 2024-12-12 07:30 UTC
Labels: bug
