### ISSUE TITLE
Acess Denied for accessing model zoo: faster_rcnn_fbnetv3a_C4.yaml

### ISSUE THREAD

**Issue by ronaldogm6** [facebookresearch/d2go#682] opened 2024-12-12 03:42 UTC
Hi i was running the code for custom training D2Go. Hereby the documentation of error.

<img width="912" alt="denied 1" src="https://github.com/user-attachments/assets/ed2b46ca-ebfd-4fe2-a40d-2e85a2b7d255" />
<img width="895" alt="denied 2" src="https://github.com/user-attachments/assets/abe6e1ee-7fe8-4165-8afa-c59f8e9d9527" />
please consider your feedback.
Thanks

**Comment by wat3rBro** [comment] 2024-12-12 07:30
Duplicate of #663

**Closed as completed by wat3rBro** 2024-12-12 07:30 UTC
Labels: documentation
